-- V 0.0.4 beta

local f = {
	["Session"] = {},
}

local __options = {
	click = {},
}

--EARRAPE
function SoundSpam()
	local ped = PLAYER.PLAYER_PED_ID()
	AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "07", ped, "DLC_GR_CS2_Sounds", true, 0)
end
--PHONE
function SoundSpamBanan()
	local ped = PLAYER.PLAYER_PED_ID()
	AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Remote_Ring", ped, "Phone_SoundSet_Michael", true, 0)
end
--ccp
function SoundSpamcrash()
	local ped = PLAYER.PLAYER_PED_ID()
	AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Crash", ped, "DLC_HEIST_HACKING_SNAKE_SOUNDS", true, 0)
end
--wasted
function SoundSpamwasted()
	local ped = PLAYER.PLAYER_PED_ID()
	AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Bed", ped, "WastedSounds", true, 0)
end
--police
function police()
	local ped = PLAYER.PLAYER_PED_ID()
	AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Microphone", ped, "POLICE_CHOPPER_CAM_SOUNDS", true, 0)
end
--10sec to end
function e10s()
	local ped = PLAYER.PLAYER_PED_ID()
	AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Timer_10s", ped, "DLC_TG_Dinner_Sounds", true, 0)
end
--doorring
function door()
	local ped = PLAYER.PLAYER_PED_ID()
	AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "DOOR_BUZZ", ped, "MP_PLAYER_APARTMENT", true, 0)
end
--wind
function wind()
	local ped = PLAYER.PLAYER_PED_ID()
	AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "WIND", ped, "CONSTRUCTION_ACCIDENT_1_SOUNDS", true, 0)
end
--wind
function fail()
	local ped = PLAYER.PLAYER_PED_ID()
	AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Trail_Custom", ped, "DLC_HEIST_HACKING_SNAKE_SOUNDS", true, 0)
	AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Background", ped, "DLC_HEIST_HACKING_SNAKE_SOUNDS", true, 0)
end

function aio()
	local ped = PLAYER.PLAYER_PED_ID()
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "07", ped, "DLC_GR_CS2_Sounds", true, 0)
	AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Remote_Ring", ped, "Phone_SoundSet_Michael", true, 0)
	AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Crash", ped, "DLC_HEIST_HACKING_SNAKE_SOUNDS", true, 0)
	AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Bed", ped, "WastedSounds", true, 0)
	AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Microphone", ped, "POLICE_CHOPPER_CAM_SOUNDS", true, 0)
	AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Timer_10s", ped, "DLC_TG_Dinner_Sounds", true, 0)
	AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "DOOR_BUZZ", ped, "MP_PLAYER_APARTMENT", true, 0)
	AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "WIND", ped, "CONSTRUCTION_ACCIDENT_1_SOUNDS", true, 0)
	AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Trail_Custom", ped, "DLC_HEIST_HACKING_SNAKE_SOUNDS", true, 0)
	AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Background", ped, "DLC_HEIST_HACKING_SNAKE_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "ACID_BATH_FALL", ped, "MICHAEL_2_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Amanda_Pulls_Away", ped, "FAMILY_6_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Architect_Fall", ped, "FBI_HEIST_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Arrive_Station", ped, "CABLE_CAR_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Attach_Cargo", ped, "DOCKS_HEIST_FINALE_2B_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Attach_Container", ped, "CRANE_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Bar_Cut", ped, "FBI_05_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Bar_Lower_And_Lock", ped, "DLC_IND_ROLLERCOASTER_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Bar_Unlock_And_Raise", ped, "DLC_IND_ROLLERCOASTER_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Beast_Cloak", ped, "APT_BvS_Soundset", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Beast_Die", ped, "APT_BvS_Soundset", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Beast_Jump", ped, "APT_BvS_Soundset", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Beast_Jump_Land", ped, "APT_BvS_Soundset", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Beast_Uncloak", ped, "APT_BvS_Soundset", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Bell", ped, "LIFT_NORMAL_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Bike_Bell", ped, "ARM_1_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "BIKER_PROP_GRIND", ped, "TREVOR_2_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Birds", ped, "ARM_1_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "BLOWOUT", ped, "BIG_SCORE_3A_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "BLOWOUT_B", ped, "BIG_SCORE_3A_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "BODY_FALL_DIVE_WATER_MASTER", ped, "docks_heist_finale_2a_sounds", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Bomb_Armed", ped, "GTAO_Speed_Convoy_Soundset", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Bomb_Disarmed", ped, "GTAO_Speed_Convoy_Soundset", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Boxcar_Door_Limit", ped, "FRANKLIN_0_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Boxcar_Door_Slide", ped, "FRANKLIN_0_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "BUILDING_SITE_CRASH", ped, "PAPARAZZO_02_SOUNDSETS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "BUS_HORN", ped, "CAR_STEAL_1_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "CAMERA_FOLEY", ped, "PAPARAZZO_02_SOUNDSETS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Car_Push_Flex", ped, "FINALE_C2_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "CAR_STEAL_1_IGNITIONS", ped, "CAR_STEAL_1_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "CAR_STEAL_3_AGENT_TYRE_BURST", ped, "CAR_STEAL_3_AGENT", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "CAR_STEAL_4_BURNOUT", ped, "CAR_STEAL_4_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Chopper_Destroyed", ped, "FBI_HEIST_FIGHT_CHOPPER_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Chopper_Goes_Down", ped, "FBI_HEIST_FIGHT_CHOPPER_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "CLOTHES_THROWN", ped, "RE_DOMESTIC_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "CLOTHES_THROWN", ped, "RE_DOMESTIC_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "CLOTHES_THROWN", ped, "RE_DOMESTIC_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "COLLAR", ped, "NIGEL_1C_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Container_Attach", ped, "CONTAINER_LIFTER_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "container_door", ped, "dlc_prison_break_heist_sounds", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Container_Impact_Land", ped, "CRANE_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Container_Land", ped, "CONTAINER_LIFTER_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Container_Release", ped, "CONTAINER_LIFTER_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "CRASH", ped, "PAPARAZZO_03A", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Crate_Collect", ped, "MP_CRATE_DROP_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Crate_Land", ped, "FBI_05_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Destroy_Cop_Car", ped, "JEWEL_HEIST_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Detach_Container", ped, "CRANE_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "DOCKS_HEIST_FINALE_2A_SUB_LAND", ped, "DOCKS_HEIST_FINALE_2A_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "DOOR_CLOSE", ped, "CABLE_CAR_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "DOOR_OPEN", ped, "CABLE_CAR_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Door_Open", ped, "Lowrider_Super_Mod_Garage_Sounds", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Door_Shut", ped, "Lowrider_Super_Mod_Garage_Sounds", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Drill_Jam", ped, "DLC_HEIST_FLEECA_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Drop_Case", ped, "JWL_PREP_2A_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "DROP_ITEMS", ped, "JEWEL_HEIST_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "DROP_STINGER", ped, "BIG_SCORE_3A_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "EMP_Vehicle_Hum", ped, "DLC_HEIST_BIOLAB_DELIVER_EMP_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Engine_fail", ped, "DLC_PILOT_ENGINE_FAILURE_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Engine_Rev", ped, "Lowrider_Super_Mod_Garage_Sounds", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Engine_Revs", ped, "DLC_HEISTS_GENERIC_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "engineexplosion", ped, "DLC_PILOT_CITY_LANDING", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Exit_Engine_Blips", ped, "Lowrider_Super_Mod_Garage_Sounds", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Flare", ped, "DLC_HEISTS_BIOLAB_FINALE_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Garage_Open", ped, "CAR_STEAL_2_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Gas_Tanker_Explosion", ped, "BIG_SCORE_3A_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Gold_Vault_Explosions", ped, "BIG_SCORE_3B_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Gold_Vault_Explosions", ped, "BIG_SCORE_3B_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Grate_Release", ped, "FBI_05_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Gunman_Bike_Crash", ped, "JEWEL_HEIST_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Hack_Success", ped, "DLC_HEIST_BIOLAB_PREP_HACKING_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "HIGHREV", ped, "PAPARAZZO_02_SOUNDSETS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Hood_Open", ped, "Lowrider_Super_Mod_Garage_Sounds", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Hood_Shut", ped, "Lowrider_Super_Mod_Garage_Sounds", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Hydraulics_Down", ped, "Lowrider_Super_Mod_Garage_Sounds", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Hydraulics_Up", ped, "Lowrider_Super_Mod_Garage_Sounds", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Keycard_Fail", ped, "DLC_HEISTS_BIOLAB_FINALE_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Keycard_Success", ped, "DLC_HEISTS_BIOLAB_FINALE_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "KISS", ped, "ROAD_RACE_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Landing_Tone", ped, "DLC_PILOT_ENGINE_FAILURE_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Leave_Station", ped, "CABLE_CAR_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Lock_Damage", ped, "JWL_PREP_2A_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Lock_Destroyed", ped, "JWL_PREP_2A_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "MINCER_FALL",ped, "MICHAEL_2_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Missile_Incoming_Hit", ped, "DOCKS_HEIST_FINALE_2B_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Missile_Incoming_Miss", ped, "DOCKS_HEIST_FINALE_2B_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Moor_Boat_Engine", ped, "DLC_Apt_Yacht_Ambient_Soundset", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Moor_Boat_Engine", ped, "DLC_Apt_Yacht_Ambient_Soundset", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Moor_SEASHARK3_Engine", ped, "DLC_Apt_Yacht_Ambient_Soundset", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Moor_SEASHARK_Engine", ped, "DLC_Apt_Yacht_Ambient_Soundset", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Muscle_Jump", ped, "BIG_SCORE_3A_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Muscle_Land", ped, "BIG_SCORE_3A_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "PASSPORT", ped, "MINUTE_02_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "PICK_UP_PARACHUTE", ped, "HUD_FRONTEND_CUSTOM_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Pierce", ped, "FAMILY_6_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Pimp_Gunshot", ped, "CAR_STEAL_2_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Pimp_Gunshot_Mic", ped, "CAR_STEAL_2_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "POLICE_CRASH",ped, "PAPARAZZO_03A", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Pt2_Fail", ped, "exile_1", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Put_On_Mask", ped, "DLC_HEISTS_GENERIC_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Radio_Off", ped, "TAXI_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Radio_On", ped, "TAXI_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Release_Crate", ped, "FBI_05_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Remote_Control_Close", ped, "PI_Menu_Sounds", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Remote_Control_Close", ped, "PI_Menu_Sounds", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Remote_Control_Fob", ped, "PI_Menu_Sounds", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Remote_Control_Open", ped, "PI_Menu_Sounds", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Remote_Control_Open", ped, "PI_Menu_Sounds", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Ride_Stop", ped, "DLC_IND_ROLLERCOASTER_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "ROPE_CUT", ped, "ROPE_CUT_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Scientist_Approaching", ped, "FBI_05_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Seagulls", ped, "JEWEL_HEIST_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Shoot_box", ped, "Paleto_Score_Setup_Sounds", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "SIREN_BLIP", ped, "BIG_SCORE_3A_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Snip_Ponytail", ped, "FAMILY_6_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "SPAWN", ped, "BARRY_01_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "SPAWN", ped, "BARRY_01_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Speech_Bubble", ped, "FBI_05_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "SPIKES", ped, "MP_RACE_SPIKES_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "spikes", ped, "CAR_THEFT_DB5_ESCAPE", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "stop", ped, "DLC_PILOT_Shooting_Range_Sounds", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Sub_Lift", ped, "DOCKS_HEIST_FINALE_2B_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "SUB_SPLASH", ped, "DOCKS_HEIST_PREP_1_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "SWAP_POSITION", ped, "DOCKS_HEIST_FINALE_2B_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "SWAP_POSITION", ped, "DOCKS_HEIST_FINALE_2B_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "TARP", ped, "JEWEL_HEIST_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Teeth_Initial_Pain", ped, "FBI_03_Torture_Sounds", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Toggle_Lights", ped, "PI_Menu_Sounds", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Tone", ped, "LIFT_POSH_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Tone", ped, "LIFT_NORMAL_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Tow_truck_damage", ped, "FBI_04_HEAT_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Trash_Bag_Land", ped, "DLC_HEIST_SERIES_A_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Trevor_2_cargo_bay_open", ped, "TREVOR_2_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Trevor_2_cargo_drop", ped, "TREVOR_2_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Trevor_2_chopper_explode", ped, "TREVOR_2_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "TREVOR_2_PLANE_START", ped, "TREVOR_2_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Trevor_2_van_rev", ped, "TREVOR_2_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "TRUCK_HORN", ped, "CAR_STEAL_1_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Truck_Stop", ped, "DOCKS_HEIST_SETUP_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Trunk_Open", ped, "Lowrider_Super_Mod_Garage_Sounds", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Trunk_Shut", ped, "Lowrider_Super_Mod_Garage_Sounds", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "tyre", ped, "CAR_THEFT_DB5_ESCAPE", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "UNHITCH_TRAILER", ped, "FAM4_UNHITCH_TRAILER", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "unlocked_bleep", ped, "HACKING_DOOR_UNLOCK_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Warning_Once", ped, "TRAIN_HORN", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "TENNIS_PLYR_BACKSLICE_MASTER", ped, "TENNIS_NPC_BACKSLICE_MASTER", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "TENNIS_PLYR_FOREARM_MASTER", ped, "TENNIS_NPC_FOREARM_MASTER", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "TENNIS_PLYR_LOB_MASTER", ped, "TENNIS_NPC_LOB_MASTER", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "TENNIS_PLYR_SMASH_BACKSLICE_MASTER", ped, "TENNIS_NPC_SMASH_BACKSLICE_MASTER", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "TENNIS_PLYR_SMASH_MASTER", ped, "TENNIS_NPC_SMASH_MASTER", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "TENNIS_PLYR_TOPSPIN_MASTER",ped, "TENNIS_NPC_TOPSPIN_MASTER", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "TENNIS_AMB_SERVE_MASTER", ped, "TENNIS_NPC_SERVE_MASTER", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "TENNIS_AMB_SMASH_MASTER", ped, "TENNIS_NPC_SMASH_MASTER", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "TENNIS_PLYR_BACKSLICE_MASTER", ped, "TENNIS_NPC_BACKSLICE_MASTER", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "TENNIS_PLYR_FOREARM_MASTER", ped, "TENNIS_NPC_FOREARM_MASTER", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "TENNIS_PLYR_LOB_MASTER", ped, "TENNIS_NPC_LOB_MASTER", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "TENNIS_PLYR_SMASH_BACKSLICE_MASTER", ped, "TENNIS_NPC_SMASH_BACKSLICE_MASTER", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "TENNIS_PLYR_SMASH_MASTER", ped, "TENNIS_NPC_SMASH_MASTER", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "TENNIS_PLYR_TOPSPIN_MASTER", ped, "TENNIS_NPC_TOPSPIN_MASTER", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "TENNIS_AMB_SERVE_MASTER", ped, "TENNIS_NPC_SERVE_MASTER", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "TENNIS_AMB_SMASH_MASTER", ped, "TENNIS_NPC_SMASH_MASTER", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "TENNIS_PLYR_BACKSLICE_MASTER", ped, "TENNIS_NPC_BACKSLICE_MASTER", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "TENNIS_PLYR_FOREARM_MASTER",ped, "TENNIS_NPC_FOREARM_MASTER", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "TENNIS_PLYR_LOB_MASTER", ped, "TENNIS_NPC_LOB_MASTER", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "TENNIS_PLYR_SMASH_BACKSLICE_MASTER", ped, "TENNIS_NPC_SMASH_BACKSLICE_MASTER", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "TENNIS_PLYR_SMASH_MASTER",ped, "TENNIS_NPC_SMASH_MASTER", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "TENNIS_PLYR_TOPSPIN_MASTER", ped, "TENNIS_NPC_TOPSPIN_MASTER", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "TENNIS_AMB_SERVE_MASTER", ped, "TENNIS_NPC_SERVE_MASTER", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "TENNIS_AMB_SMASH_MASTER", ped, "TENNIS_NPC_SMASH_MASTER", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "TENNIS_PLYR_BACKSLICE_MASTER", ped, "TENNIS_NPC_BACKSLICE_MASTER", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "TENNIS_PLYR_FOREARM_MASTER", ped, "TENNIS_NPC_FOREARM_MASTER", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "TENNIS_PLYR_LOB_MASTER", ped, "TENNIS_NPC_LOB_MASTER", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "TENNIS_PLYR_SMASH_BACKSLICE_MASTER", ped, "TENNIS_NPC_SMASH_BACKSLICE_MASTER", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "TENNIS_PLYR_SMASH_MASTER", ped, "TENNIS_NPC_SMASH_MASTER", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "TENNIS_PLYR_TOPSPIN_MASTER", ped, "TENNIS_NPC_TOPSPIN_MASTER", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "BRUSHES_SPINNING", ped, "CARWASH_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "BRUSHES_MOVE", ped, "CARWASH_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "MIND_CONTROL", ped, "BARRY_01_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "PLAYER_BEAMED_UP", ped, "BARRY_01_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "BRUSHES_HIT_CAR", ped, "CARWASH_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "YOGA_INHALE", ped, "FAMILY_5_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "YOGA_EXHALE", ped, "FAMILY_5_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "YOGA_FAIL", ped, "FAMILY_5_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "BRUSHES_SPINNING", ped, "CARWASH_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "BRUSHES_MOVE", ped, "CARWASH_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Running", ped, "CABLE_CAR_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Interior_Rain", ped, "CABLE_CAR_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Scissors", ped, "Barber_Sounds", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Makeup", ped, "Barber_Sounds", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "DRYER", ped, "CARWASH_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "SPRAY", ped, "CARWASH_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "SPRAY_CAR", ped, "CARWASH_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "GENERATOR", ped, "THE_FERRIS_WHALE_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "CARRIAGE", ped, "THE_FERRIS_WHALE_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "SLOW_SQUEAK", ped, "THE_FERRIS_WHALE_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "SLOW_SQUEAK", ped, "THE_FERRIS_WHALE_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "RAIL_LOOP", ped, "MICHAEL_2_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Rail_Loop_Skip_Start", ped, "MICHAEL_2_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "MEAT_SLIDE", ped, "MICHAEL_2_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Move", ped, "LIFT_NORMAL_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Gasmask", ped, "FBI_HEIST_RAID", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Explosion_01", ped, "FBI_HEIST_ELEVATOR_SHAFT_DEBRIS_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Land_01", ped, "FBI_HEIST_ELEVATOR_SHAFT_DEBRIS_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Explosion_02", ped, "FBI_HEIST_ELEVATOR_SHAFT_DEBRIS_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Land_02", ped, "FBI_HEIST_ELEVATOR_SHAFT_DEBRIS_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Explosion_03", ped, "FBI_HEIST_ELEVATOR_SHAFT_DEBRIS_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Land_03", ped, "FBI_HEIST_ELEVATOR_SHAFT_DEBRIS_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Explosion_04", ped, "FBI_HEIST_ELEVATOR_SHAFT_DEBRIS_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Land_04", ped, "FBI_HEIST_ELEVATOR_SHAFT_DEBRIS_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Explosion_01", ped, "FBI_HEIST_ELEVATOR_SHAFT_DEBRIS_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Land_01", ped, "FBI_HEIST_ELEVATOR_SHAFT_DEBRIS_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Explosion_01", ped, "FBI_HEIST_ELEVATOR_SHAFT_DEBRIS_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Land_01", ped, "FBI_HEIST_ELEVATOR_SHAFT_DEBRIS_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Destroy_Cop_Car", ped, "JEWEL_HEIST_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Woosh_01", ped, "FBI_HEIST_ELEVATOR_SHAFT_DEBRIS_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Woosh_02", ped, "FBI_HEIST_ELEVATOR_SHAFT_DEBRIS_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Woosh_03", ped, "FBI_HEIST_ELEVATOR_SHAFT_DEBRIS_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Woosh_04", ped, "FBI_HEIST_ELEVATOR_SHAFT_DEBRIS_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Woosh_01", ped, "FBI_HEIST_ELEVATOR_SHAFT_DEBRIS_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Woosh_01", ped, "FBI_HEIST_ELEVATOR_SHAFT_DEBRIS_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Clamp", ped, "CRANE_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Strain_No_Container", ped, "CRANE_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "GENERATOR", ped, "THE_FERRIS_WHALE_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "CARRIAGE", ped, "THE_FERRIS_WHALE_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "SLOW_SQUEAK", ped, "THE_FERRIS_WHALE_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "SLOW_SQUEAK", ped, "THE_FERRIS_WHALE_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Prop_Drop_Land", ped, "DLC_Dmod_Prop_Editor_Sounds", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Prop_Drop_Water", ped, "DLC_Dmod_Prop_Editor_Sounds", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Drill", ped, "DLC_HEIST_FLEECA_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "DOM", ped, "EXTREME_04_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "COLLECT_IN_BAG", ped, "NIGEL_1D_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "COLLECT_OUT_BAG", ped, "NIGEL_1D_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "WHISTLING", ped, "NIGEL_1B_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "move", ped, "DLC_PILOT_Shooting_Range_Sounds", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "IGNITION_FAIL", ped, "BARRY_03_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Move_L_R", ped, "CRANE_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Attach_Container_Fail", ped, "CRANE_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Move_Fail", ped, "CRANE_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Move_U_D", ped, "CRANE_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Move_Base", ped, "CRANE_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Strain", ped, "CRANE_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Scraping_Ramp", ped, "EXTREME_02_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Plane_Wind", ped, "DLC_Pilot_Chase_Parachute_Sounds", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Ejector_Scream", ped, "CAR_STEAL_3_AGENT", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Warning_Tones", ped, "DLC_PILOT_ENGINE_FAILURE_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "DEVICE", ped, "EPSILONISM_04_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "IDLE_BEEP", ped, "EPSILONISM_04_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "CONTINUAL_BEEP", ped, "EPSILONISM_04_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "SCAN", ped, "EPSILONISM_04_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Explosion_Countdown", ped, "GTAO_FM_Events_Soundset", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "CRASH", ped, "NIGEL_03_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "ALERT", ped, "SASQUATCH_01_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "RUNNING", ped, "SASQUATCH_01_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "WOUNDED", ped, "SASQUATCH_01_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "COUGH", ped, "SASQUATCH_01_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "TRAIN_COMING", ped, "NIGEL_03_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Beast_Attack", ped, "APT_BvS_Soundset", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Beast_Sprint_Loop", ped, "APT_BvS_Soundset", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "CUTTER", ped, "BIG_SCORE_3B_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Gold_Cage_Collisions", ped, "BIG_SCORE_3B_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Fire_Missile_Loop", ped, "EXILE_2_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Fire_RPG_On_Foot", ped, "EXILE_2_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Missile_Warning_Sound", ped, "EXILE_2_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Explosion_Countdown", ped, "GTAO_FM_Events_Soundset", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Biker_Ring_Tone", ped, "TREVOR_2_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Transition_Sound", ped, "EXILE_1", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Tattoo", ped, "FAMILY_6_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "ExitWater", ped, "GTAO_Hot_Tub_PED_INSIDE_WATER", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "CAR_WHEELS", ped, "FINALE_C2_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "DISTANT_RACERS", ped, "ROAD_RACE_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "DISTANT_RACERS", ped, "ROAD_RACE_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Security_Door_Bomb_Bleeps", ped, "Prologue_Sounds", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "UNZIP", ped, "FBI_01_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Armed", ped, "GTAO_Speed_Race_Sounds", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Armed", ped, "GTAO_Speed_Race_Sounds", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Count_Stop", ped, "GTAO_Speed_Race_Sounds", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Count_Stop", ped, "GTAO_Speed_Race_Sounds", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Countdown", ped, "GTAO_Speed_Race_Sounds", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Countdown", ped, "GTAO_Speed_Race_Sounds", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Explosion_Countdown", ped, "GTAO_FM_Events_Soundset", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Explosion_Timer", ped, "DLC_Lowrider_Relay_Race_Sounds", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "DOM_BREATHING", ped, "EXTREME_03_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "DOOR_BUZZ_ONESHOT_MASTER", ped, "GTAO_APT_DOOR_DOWNSTAIRS_GLASS_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Franklin_Whistle_For_Chop", ped, "SPEECH_RELATED_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "rebreather", ped, "docks_heist_finale_2a_sounds", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "foot_swish", ped, "docks_heist_finale_2a_sounds", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Attach_Cargo", ped, "docks_heist_finale_2a_sounds", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "BANK_DOOR_OPEN", ped, "BIG_SCORE_3A_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "DISTANT_RACERS", ped, "ROAD_RACE_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Gold_Trolley_Roll_Player", ped, "BIG_SCORE_3A_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Gold_Trolley_Roll_NPC", ped, "BIG_SCORE_3A_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Truck_Ramp_Scrape", ped, "BIG_SCORE_3A_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Truck_Ramp_Raise", ped, "BIG_SCORE_3A_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Truck_Ramp_Raise", ped, "BIG_SCORE_3A_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Explosion_Countdown", ped, "GTAO_FM_Events_Soundset", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Explosion_Countdown", ped, "GTAO_FM_Events_Soundset", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "LOOP_REV", ped, "PAPARAZZO_02_SOUNDSETS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "AMBIENT_SEX", ped, "PAPARAZZO_02_SOUNDSETS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Idling_Throttle_Blip_Loop", ped, "ARM_1_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Answer_Phone", ped, "Lester1B_Sounds", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Remote_Ring", ped, "Phone_SoundSet_Michael", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Torch", ped, "FBI_05_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Gasmask", ped, "FBI_05_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Foot_Swish", ped, "FBI_05_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Monkey_Scream", ped, "FBI_05_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Cable_Strain", ped, "FBI_05_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Flare", ped, "FBI_05_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "FAKE_REVS_VEHICLE_02", ped, "NIGEL_02_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Explosion_Countdown", ped, "GTAO_FM_Events_Soundset", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "CAR_STEAL_4_RAMP_SCRAPE", ped, "CAR_STEAL_4_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Beast_Calls", ped, "FM_Events_Sasquatch_Sounds", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "DEVICE",ped, "EPSILONISM_04_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "DOOR_BUZZ_ONESHOT_MASTER", ped, "GTAO_APT_DOOR_DOWNSTAIRS_GLASS_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "IDLE_BEEP_NPC", ped, "EPSILONISM_04_SOUNDSET", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Cage_Rattle", ped, "DLC_HEIST_BIOLAB_MONKEYS_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "General_Chatter", ped, "DLC_HEIST_BIOLAB_MONKEYS_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Screech", ped, "DLC_HEIST_BIOLAB_MONKEYS_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Crate_Beeps", ped, "MP_CRATE_DROP_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Crate_Beeps", ped, "MP_CRATE_DROP_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Explosion_Countdown", ped, "GTAO_FM_Events_Soundset", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Container_Impact", ped, "CRANE_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Helicopter_Wind", ped, "BASEJUMPS_SOUNDS", true, 0)
    AUDIO.PLAY_SOUND_FROM_ENTITY(-1, "Helicopter_Wind_Idle", ped, "BASEJUMPS_SOUNDS", true, 0)
end
local main_submenu = ui.add_main_submenu("Playsound")


--EARRAPE
__options.click["EarRape"] = ui.add_bool_option('Ear Rape', main_submenu, function(bool)
	f.Session.EarRape = bool
end)
--PHONE
__options.click["Banana_phone"] = ui.add_click_option('Banana Phone', main_submenu, function()
	SoundSpamBanan()
end)
--ccp
__options.click["snake_crash"] = ui.add_click_option('Atomizer', main_submenu, function()
	SoundSpamcrash()
end)
--wasted
__options.click["Falling_Crates"] = ui.add_click_option('Wasted', main_submenu, function()
	SoundSpamwasted()
end)
--police
__options.click["camera"] = ui.add_click_option('CCTV Camera', main_submenu, function()
	police()
end)
--policeheli crash
__options.click["heli"] = ui.add_click_option('10sec to end', main_submenu, function()
	e10s()
end)
--door
__options.click["door"] = ui.add_click_option('Door ring', main_submenu, function()
	door()
end)
--wind
__options.click["gate"] = ui.add_click_option('Wind', main_submenu, function()
	wind()
end)
--fail
__options.click["fail"] = ui.add_click_option('Heist hacking Snake', main_submenu, function()
	fail()
end)
--aio
__options.click["aio"] = ui.add_click_option('"ALL" sounds', main_submenu, function()
	aio()
end)
--loops
while true do

	if f.Session.EarRape then
		SoundSpam()
	end
	system.yield(10)
end