local stats = {
	----佩里科岛
	cayo = {
		only_primary = {
			diaoxiang = {
				{"H4_MISSIONS", 65413},
				{"H4CNF_APPROACH", -1},
				{"H4CNF_BS_ABIL", 63},
				{"H4CNF_BS_GEN", 63},
				{"H4CNF_WEP_DISRP", 3},
				{"H4CNF_ARM_DISRP", 3},
				{"H4CNF_HEL_DISRP", 3},
				{"H4CNF_TARGET", 5}},
			xdchongzhi = {
				{"H4_MISSIONS", 0},
				{"H4_PROGRESS", 0},
				{"H4CNF_APPROACH", 0},
				{"H4CNF_BS_ENTR", 0},
				{"H4CNF_BS_GEN", 0},
				{"H4_PLAYTHROUGH_STATUS", 0},
				{"H4CNF_TARGET", -1}}
		}
	},
	casino = {
		----名钻赌场
		diamonds = {
			aggressive = {
				{"CAS_HEIST_FLOW", -1},
				{"H3_LAST_APPROACH", 0},
				{"H3OPT_APPROACH", 3},
				{"H3_HARD_APPROACH", 0},
				{"H3OPT_TARGET", 3},
				{"H3OPT_POI", 1023},
				{"H3OPT_ACCESSPOINTS", 2047},
				{"H3OPT_CREWWEAP", 4},
				{"H3OPT_CREWDRIVER", 3},
				{"H3OPT_CREWHACKER", 4},
				{"H3OPT_DISRUPTSHIP", 3},
				{"H3OPT_BODYARMORLVL", -1},
				{"H3OPT_KEYLEVELS", 2},
				{"H3OPT_BITSET1", 799},
				{"H3OPT_BITSET0", 3670102}},
			dcchongzhi = {
				{"H3OPT_APPROACH", 0},
          		{"H3_HARD_APPROACH", 0},
            	{"H3OPT_TARGET", 0},
				{"H3OPT_POI", 0},
				{"H3OPT_ACCESSPOINTS", 0},
				{"H3OPT_BITSET1", 0},
				{"H3OPT_CREWWEAP", 0},
				{"H3OPT_CREWDRIVER", 0},
				{"H3OPT_CREWHACKER", 0},
				{"H3OPT_WEAPS", 0},
				{"H3OPT_VEHS", 0},    
				{"H3OPT_DISRUPTSHIP", 0},
				{"H3OPT_BODYARMORLVL", 0},
				{"H3OPT_KEYLEVELS", 0},
				{"H3OPT_MASKS", 0},
				{"H3OPT_BITSET0", 0}}
		}
	},
	tuner = {
		union = {{"TUNER_GEN_BS", 12543}, {"TUNER_CURRENT", 0}},
		superdollar = {{"TUNER_GEN_BS", 12543}, {"TUNER_CURRENT", 1}},
		bank_contract = {{"TUNER_GEN_BS", 12543}, {"TUNER_CURRENT", 2}},
		ecu = {{"TUNER_GEN_BS", 12543}, {"TUNER_CURRENT", 3}},
		prison = {{"TUNER_GEN_BS", 12543}, {"TUNER_CURRENT", 4}},
		agency = {{"TUNER_GEN_BS", 12543}, {"TUNER_CURRENT", 5}},
		lost = {{"TUNER_GEN_BS", 12543}, {"TUNER_CURRENT", 6}},
		data = {{"TUNER_GEN_BS", 12543}, {"TUNER_CURRENT", 7}},

		complete = {{"TUNER_GEN_BS", 0xFFFFFFF}},
		reset_gains = {{"TUNER_COUNT", 0}, {"TUNER_EARNINGS", 0}},
	},
	contract = {
		final = {{"FIXER_GENERAL_BS", -1}, {"FIXER_COMPLETED_BS", -1}, {"FIXER_STORY_BS", 4092}, {"FIXER_STORY_COOLDOWN", -1}},

		nightclub = {{"FIXER_GENERAL_BS", -1}, {"FIXER_COMPLETED_BS", -1}, {"FIXER_STORY_BS", 3}, {"FIXER_STORY_COOLDOWN", -1}},
		marina = {{"FIXER_GENERAL_BS", -1}, {"FIXER_COMPLETED_BS", -1}, {"FIXER_STORY_BS", 4}, {"FIXER_STORY_COOLDOWN", -1}},
		nightlife = {{"FIXER_GENERAL_BS", -1}, {"FIXER_COMPLETED_BS", -1}, {"FIXER_STORY_BS", 12}, {"FIXER_STORY_COOLDOWN", -1}},
		country_club = {{"FIXER_GENERAL_BS", -1}, {"FIXER_COMPLETED_BS", -1}, {"FIXER_STORY_BS", 28}, {"FIXER_STORY_COOLDOWN", -1}},
		guest_list = {{"FIXER_GENERAL_BS", -1}, {"FIXER_COMPLETED_BS", -1}, {"FIXER_STORY_BS", 60}, {"FIXER_STORY_COOLDOWN", -1}},
		high_society = {{"FIXER_GENERAL_BS", -1}, {"FIXER_COMPLETED_BS", -1}, {"FIXER_STORY_BS", 124}, {"FIXER_STORY_COOLDOWN", -1}},
		davis = {{"FIXER_GENERAL_BS", -1}, {"FIXER_COMPLETED_BS", -1}, {"FIXER_STORY_BS", 252}, {"FIXER_STORY_COOLDOWN", -1}},
		ballas = {{"FIXER_GENERAL_BS", -1}, {"FIXER_COMPLETED_BS", -1}, {"FIXER_STORY_BS", 508}, {"FIXER_STORY_COOLDOWN", -1}},
		agency_studio = {{"FIXER_GENERAL_BS", -1}, {"FIXER_COMPLETED_BS", -1}, {"FIXER_STORY_BS", 2044}, {"FIXER_STORY_COOLDOWN", -1}},
	},
	doomsday = {
		act1 = {{"GANGOPS_FLOW_MISSION_PROG", 503}, {"GANGOPS_HEIST_STATUS", -229383}, {"GANGOPS_FLOW_NOTIFICATIONS", 1557}},
		act2 = {{"GANGOPS_FLOW_MISSION_PROG", 240}, {"GANGOPS_HEIST_STATUS", -229378}, {"GANGOPS_FLOW_NOTIFICATIONS", 1557}},
		act3 = {{"GANGOPS_FLOW_MISSION_PROG", 16368}, {"GANGOPS_HEIST_STATUS", -229380}, {"GANGOPS_FLOW_NOTIFICATIONS", 1557}},
	},
	classic = {
		gongyu = {{"HEIST_PLANNING_STAGE", -1}},
		qxqiangjie = {{"CAS_HEIST_NOTS", -1}, {"CAS_HEIST_FLOW", -1}},

},
	qita = {
		xingbie = {{"ALLOW_GENDER_CHANGE", 52}},
		yezonghui = {{"CLUB_POPULARITY", 1000}},
		motuobang = {{"PAYRESUPPLYTIMER0", 1}, {"PAYRESUPPLYTIMER1", 1}, {"PAYRESUPPLYTIMER2", 1}, {"PAYRESUPPLYTIMER3", 1}, {"PAYRESUPPLYTIMER4", 1}},
		dibao = {{"PAYRESUPPLYTIMER5", 1}},
		mandiqian = {{"LIFETIME_BUY_UNDERTAKEN", 1000}, {"LIFETIME_BUY_COMPLETE", 1000}, {"LIFETIME_SELL_UNDERTAKEN", 10}, {"LIFETIME_SELL_COMPLETE", 10}, {"LIFETIME_CONTRA_EARNINGS", 28000000}},
		lianxiren = {{"FM_ACT_PHN", -1}, {"FM_ACT_PH2", -1}, {"FM_ACT_PH3", -1}, {"FM_ACT_PH4", -1}, {"FM_ACT_PH5", -1}, {"FM_VEH_TX1", -1}, {"FM_ACT_PH6", -1}, {"FM_ACT_PH7", -1}, {"FM_ACT_PH8", -1}, {"FM_ACT_PH9", -1}, {"FM_CUT_DONE", -1}, {"FM_CUT_DONE_2", -1}},
		tuzhuang = {{"XMASLIVERIES0", -1}, {"XMASLIVERIES1", -1}, {"XMASLIVERIES2", -1}, {"XMASLIVERIES3", -1}, {"XMASLIVERIES4", -1}, {"XMASLIVERIES5", -1}, {"XMASLIVERIES6", -1}, {"XMASLIVERIES7", -1}, {"XMASLIVERIES8", -1}, {"XMASLIVERIES9", -1}, {"XMASLIVERIES10", -1}, {"XMASLIVERIES11", -1}, {"XMASLIVERIES12", -1}, {"XMASLIVERIES13", -1}, {"XMASLIVERIES14", -1}, {"XMASLIVERIES15", -1}, {"XMASLIVERIES16", -1}, {"XMASLIVERIES17", -1}, {"XMASLIVERIES18", -1}, {"XMASLIVERIES19", -1}, {"XMASLIVERIES20", -1}},
		xenshen = {{"TATTOO_FM_CURRENT_32", -1}},
		youting = {{"YACHT_MISSION_PROG", 0}, {"YACHT_MISSION_FLOW", 21845}, {"CASINO_DECORATION_GIFT_1", -1}},
		tuzhuang = {{"CHAR_FM_CARMOD_1_UNLCK", -1}, {"CHAR_FM_CARMOD_2_UNLCK", -1}, {"CHAR_FM_CARMOD_3_UNLCK", -1}, {"CHAR_FM_CARMOD_4_UNLCK", -1}, {"CHAR_FM_CARMOD_5_UNLCK", -1}, {"CHAR_FM_CARMOD_6_UNLCK", -1}, {"CHAR_FM_CARMOD_7_UNLCK", -1}, {"NUMBER_TURBO_STARTS_IN_RACE", 50}, {"USJS_COMPLETED", 50}, {"AWD_FM_RACES_FASTEST_LAP", 50}, {"NUMBER_SLIPSTREAMS_IN_RACE", 100}, {"AWD_WIN_CAPTURES", 50}, {"AWD_DROPOFF_CAP_PACKAGES", 1}, {"AWD_KILL_CARRIER_CAPTURE", 1}, {"AWD_FINISH_HEISTS", 50}, {"AWD_FINISH_HEIST_SETUP_JOB", 50}, {"AWD_NIGHTVISION_KILLS", 1}, {"AWD_WIN_LAST_TEAM_STANDINGS", 50}, {"AWD_ONLY_PLAYER_ALIVE_LTS", 50}, {"AWD_FMRALLYWONDRIVE", 1}, {"AWD_FMRALLYWONNAV", 1}, {"AWD_FMWINSEARACE", 1}, {"AWD_FMWINAIRRACE", 1}, {"AWD_RACES_WON", 50}, {"RACES_WON", 50}, {"MPPLY_TOTAL_RACES_WON", 50}},
		teshu = {{"AT_FLOW_IMPEXP_NUM", 32}},
		paizhao = {{"H3OPT_ACCESSPOINTS", 0}, {"H3OPT_POI", 0}},
},

}

return stats